import type { Activity } from "./types"

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-001",
    customerId: "cust-1234",
    customerName: "John Smith",
    activityType: "Policy Created",
    description: "New auto insurance policy created - Premium coverage",
    timestamp: "2025-01-15T09:30:00Z",
    location: "Munich, Germany",
    ipAddress: "192.168.1.100",
    metadata: { policyValue: "€50,000", coverage: "Premium" },
  },
  {
    id: "act-002",
    customerId: "cust-1234",
    customerName: "John Smith",
    activityType: "Claim Filed",
    description: "Total loss claim filed for vehicle",
    timestamp: "2025-01-18T14:20:00Z",
    location: "Munich, Germany",
    ipAddress: "192.168.1.100",
    metadata: { claimAmount: "€48,000", claimType: "Total Loss" },
  },
  {
    id: "act-003",
    customerId: "cust-5678",
    customerName: "Maria Garcia",
    activityType: "Login",
    description: "Customer portal login",
    timestamp: "2025-01-20T10:15:00Z",
    location: "Madrid, Spain",
    ipAddress: "10.0.0.50",
  },
  {
    id: "act-004",
    customerId: "cust-5678",
    customerName: "Maria Garcia",
    activityType: "Login",
    description: "Customer portal login",
    timestamp: "2025-01-20T10:45:00Z",
    location: "Warsaw, Poland",
    ipAddress: "203.45.67.89",
  },
  {
    id: "act-005",
    customerId: "cust-5678",
    customerName: "Maria Garcia",
    activityType: "Bank Details Updated",
    description: "Payment bank account changed",
    timestamp: "2025-01-20T10:50:00Z",
    location: "Warsaw, Poland",
    ipAddress: "203.45.67.89",
    metadata: { previousBank: "Santander", newBank: "Unknown Bank" },
  },
  {
    id: "act-006",
    customerId: "cust-9012",
    customerName: "Thomas Mueller",
    activityType: "Policy Updated",
    description: "Home insurance coverage increased",
    timestamp: "2025-01-22T16:30:00Z",
    location: "Berlin, Germany",
    ipAddress: "172.16.0.1",
    metadata: { previousCoverage: "€200,000", newCoverage: "€500,000" },
  },
  {
    id: "act-007",
    customerId: "cust-9012",
    customerName: "Thomas Mueller",
    activityType: "Claim Filed",
    description: "Fire damage claim for home",
    timestamp: "2025-01-25T09:00:00Z",
    location: "Berlin, Germany",
    ipAddress: "172.16.0.1",
    metadata: { claimAmount: "€480,000", claimType: "Fire Damage" },
  },
]
